version: "3.7"

services:
  cockroachdb:
    image: cockroachdb/cockroach:v21.1.15
    command: start-single-node --insecure
    ports:
      - "8080:8080" # Web UI
      - "26257:26257" # CockroachDB SQL Port
    volumes:
      - cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach-data:
